# n= int(input('Digite um número: '))
# print('-' *12)
# print('{} X {:5} = {:^5}'.format(n,1,n*1))
# print('{} X {:5} = {:^5}'.format(n,2,n*2))
# print('{} X {:5} = {:^5}'.format(n,3,n*3))
# print('{} X {:5} = {:^5}'.format(n,4,n*4))
# print('{} X {:5} = {:^5}'.format(n,5,n*5))
# print('{} X {:5} = {:^5}'.format(n,6,n*6))
# print('{} X {:5} = {:^5}'.format(n,7,n*7))
# print('{} X {:5} = {:^5}'.format(n,8,n*8))
# print('{} X {:5} = {:^5}'.format(n,9,n*9))
# print('{} X {:5} = {:^5}'.format(n,10,n*10))
# print('-' *12)
n = int(input("Digite um número inteiro: "))
print('-'*12)
for i in range (0,11):
    print(f'{n} x {i:5} = {n*i:^5}')
print('-'*12)
